### ISSUE TITLE
Old values do not vanish if faulty values come in

### ISSUE THREAD

**Issue by robertauer** [clintjedwards/dht22_exporter#7] opened 2021-10-15 07:18 UTC
As long as the dht22 sensor keeps working normally, the values provided for prometheus by the exporter are updated regularly. If the sensor fails while the exporter is running and provides the exporter with invalid data, the exporter keeps on providing the last valid data to prometheus instead of providing no data at all.

**Comment by clintjedwards** [comment] 2021-10-16 04:47
Is the issue that the exporter keeps posting the last values even if the sensor is completely dead or that when the sensor providers invalid values it just provides whatever value it last reported?

Back when I wrote this the latter was intended behavior. Specifically for a temperature use case I thought it made sense to just display whatever was the last value instead of pass back a 0 and make the consumer figure out whether that 0 was legit or not.

If the former is the issue I'm sure this can be fixed by doing something simple like making the last value only last for 3 attempts or something similar.

**Comment by robertauer** [comment] 2021-10-18 05:56
I think the problem is that when the sensor provides invalid values the exporter just provides whatever value it last reported. From my perspective, the correct way for the exporter to act would be to not provide a value at all, if it can not get a valid value from the sensor. I don't know if that is possible, but providing an old value, that is not actually read from the sensor in that moment, just seems wrong.

**Comment by clintjedwards** [comment] 2021-10-19 03:34
Hmmm, I'm not sure if I agree for the reasons I mentioned above. For specifically temperature, the readings only give invalid data every so often and for that specific invalid reading I would rather the value just hold at whatever the last temperature was at (usually only a few seconds old) than return a 0(you can't just return nothing.).

If you're willing you can gate the behavior behind a flag, it should be a fairly easy feature:
1) create the flag
2) when an invalid reading is detected return 0 instead of passing the back the last value

**Comment by robertauer** [comment] 2021-10-19 06:06
Ok, I didn't know it would be impossible to just return nothing. The thing is, my sensor breaks down every once in a while for unknown reasons and the exporter keeps providing the last valid value until I notice it and restart the system, which sometimes leads to days with the exact same value in Prometheus. But I guess it would be best to replace my sensor :D

**Comment by clintjedwards** [comment] 2021-10-19 16:04
In theory, if there is an error that the sensor gives back when it has failed in your instance, you could parse for the existence of that error and then return something like a healthcheck endpoint with the exporter. Then you would just check that metric to see if the sensor was misbehaving or not and maybe tie an alert to it.

Gonna close this for now though since this is working as intended.

**Closed as completed by clintjedwards** 2021-10-19 16:04 UTC
